### ISSUE TITLE
InfoBubble size

### ISSUE THREAD

**Issue by robertnicjoo** [heremaps/maps-api-for-javascript-examples#86]
Is there any chance to change size of InfoBubble?

I wish to change `width: 300px;` but using css seems doesn't work.

```css
.H_ib_body, .H_ib_content {
  width: 300px !important;
}
```
